package com.situ.ssm.entity;

public class BanjiCourseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banji_course.banji_id
     *
     * @mbggenerated
     */
    private Integer banjiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banji_course.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji_course
     *
     * @mbggenerated
     */
    public BanjiCourseKey(Integer banjiId, Integer courseId) {
        this.banjiId = banjiId;
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji_course
     *
     * @mbggenerated
     */
    public BanjiCourseKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banji_course.banji_id
     *
     * @return the value of banji_course.banji_id
     *
     * @mbggenerated
     */
    public Integer getBanjiId() {
        return banjiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banji_course.banji_id
     *
     * @param banjiId the value for banji_course.banji_id
     *
     * @mbggenerated
     */
    public void setBanjiId(Integer banjiId) {
        this.banjiId = banjiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banji_course.course_id
     *
     * @return the value of banji_course.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banji_course.course_id
     *
     * @param courseId the value for banji_course.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji_course
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", banjiId=").append(banjiId);
        sb.append(", courseId=").append(courseId);
        sb.append("]");
        return sb.toString();
    }
}