package com.situ.ssm.mapper;

import com.situ.ssm.entity.Banji;
import com.situ.ssm.entity.BanjiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BanjiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated
     */
    int countByExample(BanjiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated
     */
    int deleteByExample(BanjiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated
     */
    int insert(Banji record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated
     */
    int insertSelective(Banji record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated
     */
    List<Banji> selectByExample(BanjiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated
     */
    Banji selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Banji record, @Param("example") BanjiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Banji record, @Param("example") BanjiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Banji record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banji
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Banji record);
}